"""add query indexes

Revision ID: cd6b842e199e
Revises: 07ec9fd570f8
Create Date: 2026-03-26 16:15:37.691775
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cd6b842e199e'
down_revision: Union[str, None] = '07ec9fd570f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ap_aging_vendor'), 'ap_aging', ['vendor'], unique=False)
    op.create_index(op.f('ix_ar_aging_customer'), 'ar_aging', ['customer'], unique=False)
    op.create_index(op.f('ix_gl_accounts_account_no'), 'gl_accounts', ['account_no'], unique=True)
    op.create_index(op.f('ix_gl_balances_account_no'), 'gl_balances', ['account_no'], unique=False)
    op.create_index(op.f('ix_gl_balances_period'), 'gl_balances', ['period'], unique=False)
    op.create_index(op.f('ix_pl_items_business_line'), 'pl_items', ['business_line'], unique=False)
    op.create_index('ix_pl_items_cat_period', 'pl_items', ['category', 'period'], unique=False)
    op.create_index(op.f('ix_pl_items_period'), 'pl_items', ['period'], unique=False)
    op.create_index(op.f('ix_platform_revenue_period'), 'platform_revenue', ['period'], unique=False)
    op.create_index('ix_platform_revenue_plat_period', 'platform_revenue', ['platform', 'period'], unique=False)
    op.create_index(op.f('ix_platform_revenue_platform'), 'platform_revenue', ['platform'], unique=False)
    op.create_index(op.f('ix_production_costs_video_id'), 'production_costs', ['video_id'], unique=False)
    op.create_index(op.f('ix_recon_records_period'), 'recon_records', ['period'], unique=False)
    op.create_index('ix_recon_records_plat_period', 'recon_records', ['platform', 'period'], unique=False)
    op.create_index(op.f('ix_recon_records_platform'), 'recon_records', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recon_records_platform'), table_name='recon_records')
    op.drop_index('ix_recon_records_plat_period', table_name='recon_records')
    op.drop_index(op.f('ix_recon_records_period'), table_name='recon_records')
    op.drop_index(op.f('ix_production_costs_video_id'), table_name='production_costs')
    op.drop_index(op.f('ix_platform_revenue_platform'), table_name='platform_revenue')
    op.drop_index('ix_platform_revenue_plat_period', table_name='platform_revenue')
    op.drop_index(op.f('ix_platform_revenue_period'), table_name='platform_revenue')
    op.drop_index(op.f('ix_pl_items_period'), table_name='pl_items')
    op.drop_index('ix_pl_items_cat_period', table_name='pl_items')
    op.drop_index(op.f('ix_pl_items_business_line'), table_name='pl_items')
    op.drop_index(op.f('ix_gl_balances_period'), table_name='gl_balances')
    op.drop_index(op.f('ix_gl_balances_account_no'), table_name='gl_balances')
    op.drop_index(op.f('ix_gl_accounts_account_no'), table_name='gl_accounts')
    op.drop_index(op.f('ix_ar_aging_customer'), table_name='ar_aging')
    op.drop_index(op.f('ix_ap_aging_vendor'), table_name='ap_aging')
    # ### end Alembic commands ###
